import { SectorData } from './types';

export const SECTORS: SectorData[] = [
  {
    id: 'intro',
    type: 'analysis',
    title: 'Chicago Growth Capital',
    shortTitle: 'Overview',
    overview: "64 verified deals. $2.99 billion disclosed. Six sectors. One year of tracking, verification, and a growing awareness of how much 'funding data' is really an argument about definitions.",
    stats: [
      { label: 'Verified Deals', value: '64', trend: 'stable', trendValue: '2025' },
      { label: 'Disclosed Capital', value: '$2.99B', trend: 'stable', trendValue: 'Total' },
      { label: 'Sectors', value: '6', trend: 'stable', trendValue: 'Tracked' },
    ],
    chartData: [
      { year: '2020', value: 1.8 },
      { year: '2021', value: 4.2 },
      { year: '2022', value: 3.1 },
      { year: '2023', value: 2.4 },
      { year: '2024', value: 2.7 },
      { year: '2025', value: 2.99 },
    ],
    chartLabel: 'Capital by Year ($bn)',
    startups: [],
    insights: "That headline comes with a warning label. One private equity recap accounts for more than half the total.",
    futureTrend: "Remove it and the story changes immediately.",
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=2613&auto=format&fit=crop',
  },
  {
    id: 'thesis',
    type: 'editorial',
    title: 'The Numbers Are Not the Story',
    shortTitle: 'Thesis',
    overview: "They're the flashlight. And like every flashlight, they throw a bright cone on one corner of the room while leaving the rest in shadow.<br/><br/>That's what this project is: a year spent trying to see Chicago's 2025 capital picture with the tools most people don't have. No PitchBook license. No Crunchbase subscription. Just obsessive tracking, verification, and a growing awareness of how much 'funding data' is really an argument about definitions.<br/><br/>We tracked 64 verified deals and landed at <strong>$2.99B</strong> in disclosed growth capital across six sectors. That headline comes with a warning label. A single mega-deal can account for more than half the total in a year like this. Remove the largest transaction and the story changes immediately. That's the point: totals are not neutral. They can describe momentum, but they can also mask it.",
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'complexity',
    type: 'editorial',
    title: 'Capital Is a Many-Headed Creature',
    shortTitle: 'Complexity',
    overview: "So the thesis doesn't move. Chicago is showing signs of rebound, but 'growth' is a slippery word, and capital is a many-headed creature. Equity is only one head.<br/><br/>Debt facilities, recapitalizations, strategic checks, and grants move the ecosystem too—often quietly, often without the applause of a big Series B headline. This review is an attempt to confront the numbers without worshiping them, to name what we can verify, and to admit what we can't.<br/><br/>The shadow economy of undisclosed rounds still exists, meaning the real total is probably larger than any public report, including this one.",
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'methodology',
    type: 'editorial',
    title: 'What We Can Verify, Infer, and Cannot Measure',
    shortTitle: 'Method',
    overview: "The modern temptation is to demand one number that tells the whole story. Chicago's 2025 funding landscape refuses to cooperate.<br/><br/>So instead of forcing a clean narrative onto a messy reality, this retrospective breaks the year into component parts: what we can verify, what we can infer, and what we cannot measure without privileged data access.<br/><br/>Together they offer one claim: <strong>Chicago's capital picture is more complex than the headlines suggest</strong>, and the most important parts of the story may be hiding in the unreported, the early-stage, and the quiet forms of growth.",
    image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'definitions',
    type: 'editorial',
    title: 'Operational Definitions',
    shortTitle: 'Definitions',
    overview: "<strong>Growth capital</strong> — Any disclosed capital that materially supported a Chicago-area company's growth in 2025, across multiple instruments: equity, debt, PE recaps, strategic capital, and disclosed grants. We use this term to reflect how companies actually finance scaling, not just how venture funding is typically reported.<br/><br/><strong>Equity</strong> — Capital invested in exchange for ownership. Priced funding rounds that increase a company's capitalization.<br/><br/><strong>Debt / Debt facility</strong> — Borrowed capital that must be repaid. A facility describes capacity—the amount available—not necessarily the amount drawn.<br/><br/><strong>Venture debt</strong> — Debt structured for high-growth companies. Treated as debt, not equity.<br/><br/><strong>Private equity recapitalization</strong> — A PE-led transaction that materially changes a company's capital structure. Counted as growth capital when it represents capital deployed into a Chicago-area company.<br/><br/><strong>Disclosed vs undisclosed</strong> — Disclosed means the amount is public. Undisclosed means the deal is confirmed but the amount is not public.<br/><br/><em>This list is intentionally narrow. It defines how terms are used inside this review. For broader definitions, see the ChiStartupHub glossary.</em>",
    image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'healthtech',
    type: 'analysis',
    title: 'Healthcare Led by Deal Count',
    shortTitle: 'Health',
    overview: "18 of our 64 deals were in healthcare, biotech, or medtech. That's 28% of deal activity. The dollars are more modest—$433M total—because many are early-stage. University spinouts from UChicago and Northwestern are a real pipeline here.",
    stats: [
      { label: 'Deals', value: '18', trend: 'stable', trendValue: '28% of total' },
      { label: 'Disclosed', value: '$433M', trend: 'stable', trendValue: '14% of dollars' },
    ],
    chartData: [
      { year: 'BioTech', value: 305, label: '$305M (3 deals)' },
      { year: 'Devices', value: 39.6, label: '$39.6M (4 deals)' },
      { year: 'Digital', value: 48.4, label: '$48.4M (4 deals)' },
      { year: 'Imaging', value: 31.5, label: '$31.5M (1 deal)' },
      { year: 'Surgical', value: 5.3, label: '$5.3M (2 deals)' },
    ],
    chartLabel: 'Sub-sector ($M)',
    startups: [
      { name: 'Triana Biomedicines', description: 'Protein degradation therapeutics', funding: '$120M Series B' },
      { name: 'Pelage Pharmaceuticals', description: 'Regenerative medicine', funding: '$120M Series B' },
      { name: 'Gate Bioscience', description: 'Oral molecular gate', funding: '$65M Series B' },
      { name: 'Sibel Health', description: 'Wearable monitoring', funding: '$39M Series C Ext' },
      { name: 'HOPPR', description: 'Medical imaging AI', funding: '$31.5M Series A' },
    ],
    insights: "Drug discovery raised the largest rounds. Device companies stayed smaller.",
    futureTrend: "University tech transfer remains the engine here.",
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=2680&auto=format&fit=crop',
  },
  {
    id: 'fintech',
    type: 'analysis',
    title: 'FinTech: Few Deals, Big Dollars',
    shortTitle: 'FinTech',
    overview: "11 deals but $1.53B—half our total. Zero Hash reached unicorn status. GeoWealth got BlackRock backing. Chicago's trading heritage shows up in the deal flow. But 11 deals across a whole year isn't exactly a flood.",
    stats: [
      { label: 'Deals', value: '11', trend: 'stable', trendValue: '17% of total' },
      { label: 'Disclosed', value: '$1.53B', trend: 'stable', trendValue: '51% of dollars' },
    ],
    chartData: [
      { year: 'Crypto', value: 164.6, label: '$164.6M (3 deals)' },
      { year: 'Wealth', value: 38, label: '$38M (2 deals)' },
      { year: 'Payments', value: 25, label: '$25M (2 deals)' },
      { year: 'Lending', value: 100, label: '$100M (1 deal)' },
      { year: 'Creator', value: 6, label: '$6M (1 deal)' },
    ],
    chartLabel: 'Sub-sector ($M)',
    startups: [
      { name: 'Zero Hash', description: 'Crypto infrastructure', funding: '$104M + $54.6M Series D' },
      { name: 'Bonside', description: 'Alternative lending', funding: '$100M Facility' },
      { name: 'GeoWealth', description: 'TAMP platform', funding: '$38M Series C' },
      { name: 'Coinflow Labs', description: 'Web3 payments', funding: '$25M Series A' },
      { name: 'Loop Crypto', description: 'Crypto payments', funding: '$6M Series A' },
    ],
    insights: "Zero Hash alone is $158M. Without it, FinTech looks more modest.",
    futureTrend: "Crypto infrastructure continues to be the Chicago FinTech story.",
    image: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'enterprise',
    type: 'analysis',
    title: 'Enterprise Software: The Nerdio Effect',
    shortTitle: 'Enterprise',
    overview: "Nerdio's $500M Series C is 89% of this category. It's a real company with real revenue, but it makes the sector look bigger than the underlying activity. Without Nerdio: $58M across 9 deals. With Nerdio: $558M across 10 deals. Context matters.",
    stats: [
      { label: 'Deals', value: '10', trend: 'stable', trendValue: '16% of total' },
      { label: 'Disclosed', value: '$558M', trend: 'stable', trendValue: '19% of dollars' },
    ],
    chartData: [
      { year: 'Cloud/IT', value: 500, label: '$500M (Nerdio)' },
      { year: 'Analytics', value: 42.1, label: '$42.1M (Ocient)' },
      { year: 'Sales', value: 10.6, label: '$10.6M (Letter AI)' },
      { year: 'AI/Auto', value: 5.25, label: '$5.25M (3 deals)' },
    ],
    chartLabel: 'Sub-sector ($M)',
    startups: [
      { name: 'Nerdio', description: 'Cloud IT management', funding: '$500M Series C' },
      { name: 'Ocient', description: 'Hyperscale analytics', funding: '$42.1M Series B Ext' },
      { name: 'Letter AI', description: 'Sales enablement', funding: '$10.6M Series A' },
      { name: 'Silkline', description: 'AI automation', funding: '$4M Seed' },
    ],
    insights: "One mega-deal can define an entire sector's numbers.",
    futureTrend: "Early-stage AI companies are the pipeline to watch.",
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'deeptech',
    type: 'analysis',
    title: 'Deep Tech: Quantum Is Real Here',
    shortTitle: 'Deep Tech',
    overview: "Pasqal moved its US headquarters to Chicago. Infleqtion is building quantum systems. State incentives played a role. 6 deals, $182M. Not huge volume, but these are long-horizon bets that don't fit the typical startup mold.",
    stats: [
      { label: 'Deals', value: '6', trend: 'stable', trendValue: '9% of total' },
      { label: 'Disclosed', value: '$182M', trend: 'stable', trendValue: '6% of dollars' },
    ],
    chartData: [
      { year: 'Quantum', value: 115, label: '$115M (2 deals)' },
      { year: 'Materials', value: 9.1, label: '$9.1M (1 deal)' },
      { year: 'Nanotech', value: 1.24, label: '$1.24M (1 deal)' },
      { year: 'Neurotech', value: 1.3, label: '$1.3M (1 deal)' },
    ],
    chartLabel: 'Sub-sector ($M)',
    startups: [
      { name: 'Pasqal', description: 'Quantum computing (France HQ)', funding: '$65M US Expansion' },
      { name: 'Infleqtion', description: 'Quantum systems', funding: '$50M Corporate' },
      { name: 'SUN METALON', description: 'Metal manufacturing', funding: '$9.1M Series A' },
      { name: 'NanoPattern', description: 'Nanotechnology', funding: '$1.24M NSF Grant' },
    ],
    insights: "Illinois is positioning for quantum. Whether it pays off is years away.",
    futureTrend: "Government and institutional backing matter more here than traditional VC.",
    image: 'https://images.unsplash.com/photo-1596236560934-8c8f5f1c990c?q=80&w=2574&auto=format&fit=crop',
  },
  {
    id: 'bigdeals',
    type: 'analysis',
    title: 'The Deals That Skew Everything',
    shortTitle: 'Big Deals',
    overview: "Three deals account for $2.35B—79% of our total. HUB International ($1.6B PE), Nerdio ($500M), and Kin Insurance ($250M combined). If you want to understand 'Chicago funding,' you have to decide whether these count the same as a $2M seed round. We included them. Others might not.",
    stats: [
      { label: 'Top 3 Deals', value: '$2.35B', trend: 'stable', trendValue: '79% of total' },
      { label: 'Other 61', value: '$640M', trend: 'stable', trendValue: '21% of total' },
    ],
    chartData: [
      { year: 'HUB Intl', value: 1600, label: '$1.6B PE' },
      { year: 'Nerdio', value: 500, label: '$500M Series C' },
      { year: 'Kin', value: 250, label: '$250M (equity+debt)' },
      { year: 'Zero Hash', value: 158.6, label: '$158.6M Series D' },
      { year: 'Other 60', value: 481.4, label: '$481.4M combined' },
    ],
    chartLabel: 'Deal Size ($M)',
    startups: [
      { name: 'HUB International', description: 'Insurance brokerage PE recap', funding: '$1.6B PE' },
      { name: 'Nerdio', description: 'Cloud IT (Unicorn)', funding: '$500M Series C' },
      { name: 'Kin Insurance', description: 'Home insurance (Unicorn)', funding: '$50M + $200M debt' },
      { name: 'Zero Hash', description: 'Crypto (Unicorn)', funding: '$104M + $54.6M' },
    ],
    insights: "Concentration is extreme. A few deals define the headline number.",
    futureTrend: "Next year's total will depend heavily on whether any mega-deals happen.",
    image: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?q=80&w=2673&auto=format&fit=crop',
  },
  {
    id: 'limitations',
    type: 'editorial',
    title: 'Public Verification Has Limits',
    shortTitle: 'Limits',
    overview: "This review is built from public verification. We started with a larger set of reported deals, then validated each entry using primary sources when available—SEC filings and company announcements—supported by credible reporting.<br/><br/>We removed deals that could not be confirmed, were misattributed to Chicago, or belonged to a different year. Amounts are recorded as disclosed when public; when amounts were not public, the deal is included as undisclosed.<br/><br/>Public verification improves reliability but cannot capture deals that were never publicly documented. The shadow economy of unreported rounds means the real total is probably larger than any public report, including this one.",
    image: 'https://images.unsplash.com/photo-1505236273191-1dce886b01e9?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'corrections',
    type: 'editorial',
    title: 'What We Got Wrong (And Fixed)',
    shortTitle: 'Corrections',
    overview: "We started with more deals than we ended with. After verification, we removed 15+ entries that didn't hold up to scrutiny.<br/><br/>Some were companies incorrectly attributed to Chicago. Some were rounds from previous years that got mislabeled. Some simply had no verifiable source—just aggregator listings with no primary documentation.<br/><br/>We also corrected funding amounts, lead investors, and deal dates where our initial data was wrong. The current dataset reflects those fixes. It's more accurate than what we started with, though certainly not perfect.",
    image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'context',
    type: 'editorial',
    title: 'The Bigger Picture',
    shortTitle: 'Context',
    overview: "John Pletz at Crain's reported Chicago VC hit a 7-year low in 2025. PitchBook data showed $2.6B across 311 deals, down from $3.3B in 2024. US VC overall was up 59% to $339B.<br/><br/>Our $2.99B figure differs because we're counting different things—we include PE recaps, debt facilities, and strategic capital that pure VC tallies exclude. Different methodologies, different totals.<br/><br/>Chicago isn't keeping pace with the coasts. Austin, Boston, Seattle, NYC all grew while Chicago contracted. That's the context our numbers exist within.<br/><br/><em>Sources: Crain's Chicago Business, PitchBook-NVCA Venture Monitor, Start Midwest</em>",
    image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'stages',
    type: 'analysis',
    title: 'Early Stage Is the Base',
    shortTitle: 'Stages',
    overview: "59% of our deals are Seed or Series A. Average early-stage deal: $7M. The pipeline exists. Whether these companies stay in Chicago as they scale is a different question that data alone can't answer.",
    stats: [
      { label: 'Early Stage', value: '59%', trend: 'stable', trendValue: '38 deals' },
      { label: 'Avg Size', value: '$7M', trend: 'stable', trendValue: 'Seed/A' },
    ],
    chartData: [
      { year: 'Pre-Seed', value: 4, label: '4 deals (6%)' },
      { year: 'Seed/A', value: 38, label: '38 deals (59%)' },
      { year: 'Growth', value: 11, label: '11 deals (17%)' },
      { year: 'Late', value: 5, label: '5 deals (8%)' },
      { year: 'PE', value: 6, label: '6 deals (9%)' },
    ],
    chartLabel: 'Stage Distribution',
    startups: [],
    insights: "Lots of seeds planted. The harvest is years away.",
    futureTrend: "2027-2028 will show if this cohort scaled or scattered.",
    image: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=2646&auto=format&fit=crop',
  },
];
