import { SectorData } from './types';

export const SECTORS: SectorData[] = [
  {
    id: 'intro',
    type: 'analysis',
    title: 'Capital Access: The Real Numbers',
    shortTitle: 'Overview',
    overview: "Forget the hype cycles. This is what actually happened in Chicago venture capital in 2025. We verified 64 deals, removed 11 that couldn't pass scrutiny, and tracked nearly $3 billion in disclosed funding. Three unicorns. 18 healthcare deals. A quantum computing hub emerging in the heartland. These aren't projections—they're receipts.",
    stats: [
      { label: 'Total Disclosed', value: '$2.99B', trend: 'up', trendValue: '64 Verified Deals' },
      { label: 'Unicorns', value: '3', trend: 'up', trendValue: 'Nerdio, Kin, Zero Hash' },
      { label: 'Top Sector', value: 'HealthTech', trend: 'stable', trendValue: '28% of Deals' },
    ],
    chartData: [
      { year: '2020', value: 1.8 },
      { year: '2021', value: 4.2 },
      { year: '2022', value: 3.1 },
      { year: '2023', value: 2.4 },
      { year: '2024', value: 2.7 },
      { year: '2025', value: 2.99 },
    ],
    chartLabel: 'Capital Disclosed ($bn)',
    startups: [],
    insights: "79.7% verification rate after extended due diligence. We removed deals that were wrong geography, wrong year, or unverifiable.",
    futureTrend: "The 'Chicago Model'—revenue-first, hype-second—is proving resilient.",
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=2613&auto=format&fit=crop',
  },
  {
    id: 'healthtech',
    type: 'analysis',
    title: 'HealthTech: Chicago\'s Quiet Giant',
    shortTitle: 'HealthTech',
    overview: "28% of all deals. Drug discovery, medical devices, digital health. The university spinout pipeline from UChicago and Northwestern is producing real companies with real revenue. Protein degradation. Regenerative medicine. Wearable platforms. This isn't coastal biotech theater—it's Midwestern clinical validation.",
    stats: [
      { label: 'Deal Count', value: '18', trend: 'up', trendValue: '28.1% of Total' },
      { label: 'Disclosed', value: '$433M', trend: 'up', trendValue: '14.5% of Dollars' },
    ],
    chartData: [
      { year: 'BioTech', value: 305, label: '$305M (3 deals)' },
      { year: 'Medical Devices', value: 39.6, label: '$39.6M (4 deals)' },
      { year: 'Digital Health', value: 48.4, label: '$48.4M (4 deals)' },
      { year: 'Medical Imaging', value: 31.5, label: '$31.5M (1 deal)' },
      { year: 'Surgical Tech', value: 5.3, label: '$5.3M (2 deals)' },
    ],
    chartLabel: 'Sub-sector Funding ($M)',
    startups: [
      { name: 'Triana Biomedicines', description: 'Protein degradation therapeutics', funding: '$120M Series B' },
      { name: 'Pelage Pharmaceuticals', description: 'Regenerative medicine for hair loss', funding: '$120M Series B' },
      { name: 'Gate Bioscience', description: 'Oral molecular gate technology', funding: '$65M Series B' },
      { name: 'Sibel Health', description: 'Wearable clinical monitoring platform', funding: '$39M Series C Ext' },
      { name: 'HOPPR', description: 'AI infrastructure for medical imaging', funding: '$31.5M Series A' },
    ],
    insights: "Drug discovery companies raising the largest rounds. Northwestern and UChicago spinouts dominating early stage.",
    futureTrend: "Watch for protein degradation and regenerative medicine to consolidate.",
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=2680&auto=format&fit=crop',
  },
  {
    id: 'editorial-1',
    type: 'editorial',
    title: 'The Verification Problem',
    shortTitle: 'Truth',
    overview: "We started with 75 deals. We ended with 64. <br/><br/> 11 deals removed: <strong>2 wrong geography</strong> (Stockholm companies claiming Chicago), <strong>4 wrong year</strong> (2021-2024 rounds recycled as 2025), <strong>5 unverifiable</strong> (no press release, no SEC filing, no confirmation). <br/><br/> This is what data integrity looks like. <strong>The number you can't verify is worse than no number at all.</strong>",
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'fintech',
    type: 'analysis',
    title: 'FinTech: Where the Money Is',
    shortTitle: 'FinTech',
    overview: "17% of deals but 51% of dollars. That's the FinTech story. Zero Hash reached unicorn status. Crypto infrastructure. WealthTech platforms. Alternative lending. Chicago's trading heritage translates directly into financial technology—these aren't FOMO plays, they're infrastructure bets.",
    stats: [
      { label: 'Deal Count', value: '11', trend: 'up', trendValue: '17.2% of Total' },
      { label: 'Disclosed', value: '$1.53B', trend: 'up', trendValue: '51.3% of Dollars' },
    ],
    chartData: [
      { year: 'Crypto/Blockchain', value: 164.6, label: '$164.6M (3 deals)' },
      { year: 'WealthTech', value: 38, label: '$38M (2 deals)' },
      { year: 'Payments', value: 25, label: '$25M (2 deals)' },
      { year: 'Alt Lending', value: 100, label: '$100M facility (1 deal)' },
      { year: 'Creator Economy', value: 6, label: '$6M (1 deal)' },
    ],
    chartLabel: 'Sub-sector Funding ($M)',
    startups: [
      { name: 'Zero Hash', description: 'Crypto infrastructure platform', funding: '$104M + $54.6M Series D' },
      { name: 'Bonside', description: 'Brick-and-mortar alternative lending', funding: '$100M Facility' },
      { name: 'GeoWealth', description: 'TAMP platform (BlackRock-backed)', funding: '$38M Series C' },
      { name: 'Coinflow Labs', description: 'Web3 payment infrastructure', funding: '$25M Series A' },
      { name: 'Loop Crypto', description: 'Crypto payments (VanEck-backed)', funding: '$6M Series A' },
    ],
    insights: "Zero Hash validated at unicorn level. Chicago trading firms driving institutional crypto adoption.",
    futureTrend: "Embedded finance for legacy industries will be the next frontier.",
    image: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'enterprise',
    type: 'analysis',
    title: 'Enterprise Software: The Nerdio Effect',
    shortTitle: 'Enterprise',
    overview: "One deal dominates: Nerdio's $500M Series C at unicorn valuation. But look deeper—Ocient's hyperscale analytics, Letter AI's sales enablement, a cluster of AI/automation plays. Chicago enterprise software isn't flashy, but it's building infrastructure that companies actually pay for.",
    stats: [
      { label: 'Deal Count', value: '10', trend: 'stable', trendValue: '15.6% of Total' },
      { label: 'Disclosed', value: '$558M', trend: 'up', trendValue: '18.7% of Dollars' },
    ],
    chartData: [
      { year: 'Cloud/IT', value: 500, label: '$500M (Nerdio)' },
      { year: 'Data/Analytics', value: 42.1, label: '$42.1M (Ocient)' },
      { year: 'AI/Automation', value: 5.25, label: '$5.25M (3 deals)' },
      { year: 'Sales Enablement', value: 10.6, label: '$10.6M (Letter AI)' },
    ],
    chartLabel: 'Sub-sector Funding ($M)',
    startups: [
      { name: 'Nerdio', description: 'Cloud IT management (Microsoft partner)', funding: '$500M Series C' },
      { name: 'Ocient', description: 'Hyperscale data analytics platform', funding: '$42.1M Series B Ext' },
      { name: 'Letter AI', description: 'AI-powered sales enablement', funding: '$10.6M Series A' },
      { name: 'Silkline', description: 'AI automation platform', funding: '$4M Seed' },
      { name: 'Sphera', description: 'ESG software (Blackstone PE)', funding: 'PE Recap' },
    ],
    insights: "Nerdio alone is 89% of sector dollars. Enterprise AI still early-stage in Chicago.",
    futureTrend: "Vertical-specific AI applications will emerge from current platform plays.",
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'editorial-2',
    type: 'editorial',
    title: 'The Stage Story',
    shortTitle: 'Stages',
    overview: "<strong>59% of deals are early stage</strong> (Seed/Series A). Average early-stage deal: $7M. <br/><br/> But the dollars tell a different story: Late-stage and PE deals capture the bulk of capital. <strong>HUB International's $1.6B alone is 54% of total disclosed funding.</strong> <br/><br/> Chicago has a strong angel and accelerator ecosystem feeding the pipeline. The question: Can these early-stage companies stay and scale here, or will they drift to the coasts?",
    image: 'https://images.unsplash.com/photo-1505236273191-1dce886b01e9?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'deeptech',
    type: 'analysis',
    title: 'Deep Tech: The Quantum Bet',
    shortTitle: 'Deep Tech',
    overview: "Illinois is becoming a quantum computing hub. Full stop. Pasqal (French company) established US headquarters here. Infleqtion is building utility-scale quantum systems. Add advanced materials, nanotechnology, and neurotech—Chicago's research universities are translating basic science into venture-backable companies.",
    stats: [
      { label: 'Deal Count', value: '6', trend: 'up', trendValue: '9.4% of Total' },
      { label: 'Disclosed', value: '$182M', trend: 'up', trendValue: '6.1% of Dollars' },
    ],
    chartData: [
      { year: 'Quantum', value: 115, label: '$115M (2 deals)' },
      { year: 'Adv Materials', value: 9.1, label: '$9.1M (1 deal)' },
      { year: 'Nanotech', value: 1.24, label: '$1.24M (1 deal)' },
      { year: 'Neurotech', value: 1.3, label: '$1.3M (1 deal)' },
    ],
    chartLabel: 'Sub-sector Funding ($M)',
    startups: [
      { name: 'Pasqal', description: 'Neutral atom quantum computing (France→Chicago)', funding: '$65M US Expansion' },
      { name: 'Infleqtion', description: 'Utility-scale quantum systems', funding: '$50M Corporate' },
      { name: 'SUN METALON', description: 'Next-gen metal manufacturing', funding: '$9.1M Series A' },
      { name: 'NanoPattern Technologies', description: 'Nanotechnology (Evanston)', funding: '$1.24M NSF Grant' },
      { name: 'Graymatter Labs', description: 'Brain-computer interfaces', funding: '$1.3M Seed' },
    ],
    insights: "State incentives and IFA support driving quantum expansion. Universities critical for talent pipeline.",
    futureTrend: "Quantum advantage demonstrations expected 2026-2027. Chicago positioned for early applications in finance.",
    image: 'https://images.unsplash.com/photo-1596236560934-8c8f5f1c990c?q=80&w=2574&auto=format&fit=crop',
  },
  {
    id: 'insurance',
    type: 'analysis',
    title: 'Insurance & InsurTech: The Mega-Deals',
    shortTitle: 'Insurance',
    overview: "Two unicorns. One $1.6 billion PE recapitalization. Insurance might be the least glamorous sector, but it's where Chicago's institutional capital really shows up. HUB International's deal alone represents 54% of all disclosed funding. Kin Insurance continues its growth trajectory in home insurance. This is Chicago's financial heritage in action.",
    stats: [
      { label: 'Deal Count', value: '3', trend: 'stable', trendValue: '4.7% of Total' },
      { label: 'Disclosed', value: '$1.85B', trend: 'up', trendValue: '62% of Dollars' },
    ],
    chartData: [
      { year: 'Insurance PE', value: 1600, label: '$1.6B (HUB)' },
      { year: 'InsurTech Equity', value: 50, label: '$50M (Kin)' },
      { year: 'InsurTech Debt', value: 200, label: '$200M (Kin)' },
    ],
    chartLabel: 'Deal Breakdown ($M)',
    startups: [
      { name: 'HUB International', description: 'Insurance brokerage (PE recap)', funding: '$1.6B PE' },
      { name: 'Kin Insurance', description: 'Home insurance (Unicorn $2B+)', funding: '$50M Series E' },
      { name: 'Kin Insurance', description: 'Debt facility', funding: '$200M Debt' },
    ],
    insights: "HUB skews all sector analysis. Without it, total disclosed funding drops to $1.39B.",
    futureTrend: "Climate risk insurance tech emerging as next wave of Chicago InsurTech.",
    image: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?q=80&w=2646&auto=format&fit=crop',
  },
  {
    id: 'editorial-3',
    type: 'editorial',
    title: 'What We Got Wrong',
    shortTitle: 'Corrections',
    overview: "Transparency matters. Here's what we corrected: <br/><br/> <strong>Loop Crypto:</strong> $8M → $6M (verified via Blockworks) <br/> <strong>OrisDX:</strong> Lead investor corrected to Revere Partners <br/> <strong>JusticeBid:</strong> Typo fixed (OnDeck → OnDean Forward) <br/> <strong>Amylu Foods:</strong> Lead corrected to TowerBrook <br/> <strong>ghSMART:</strong> Lead corrected to KKR (Ascendant) <br/> <strong>Dude Products:</strong> Lead corrected to TSG Consumer Partners <br/><br/> <strong>Net change: -$24.44M from original estimates.</strong>",
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2670&auto=format&fit=crop',
  },
  {
    id: 'unicorns',
    type: 'analysis',
    title: 'The Three Unicorns',
    shortTitle: 'Unicorns',
    overview: "Three companies crossed the billion-dollar threshold with verified funding rounds in 2025. Nerdio hit it with a $500M Series C. Zero Hash validated it with a $104M Series D. Kin Insurance continues to scale. These aren't paper valuations from the hype era—they're backed by growth-stage investors putting real capital to work.",
    stats: [
      { label: 'Nerdio', value: '$1B+', trend: 'up', trendValue: 'Cloud IT Management' },
      { label: 'Kin Insurance', value: '$2B+', trend: 'up', trendValue: 'Home InsurTech' },
      { label: 'Zero Hash', value: '$1B+', trend: 'up', trendValue: 'Crypto Infrastructure' },
    ],
    chartData: [
      { year: 'Nerdio', value: 500, label: '$500M Series C' },
      { year: 'Zero Hash', value: 158.6, label: '$158.6M (D + ext)' },
      { year: 'Kin Insurance', value: 250, label: '$250M (equity + debt)' },
    ],
    chartLabel: '2025 Funding ($M)',
    startups: [
      { name: 'Nerdio', description: 'Microsoft cloud IT management platform', funding: '$500M Series C (General Atlantic)' },
      { name: 'Zero Hash', description: 'B2B crypto infrastructure for financial institutions', funding: '$104M + $54.6M Series D (Interactive Brokers)' },
      { name: 'Kin Insurance', description: 'Direct-to-consumer home insurance tech', funding: '$50M Series E + $200M Debt (QED, Wellington)' },
    ],
    insights: "All three unicorns are B2B/infrastructure plays, not consumer apps. This is the Chicago DNA.",
    futureTrend: "Watch for potential IPO activity in 2026-2027 from this cohort.",
    image: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?q=80&w=2673&auto=format&fit=crop',
  },
  {
    id: 'conclusion',
    type: 'analysis',
    title: 'The Bottom Line',
    shortTitle: 'Summary',
    overview: "64 verified deals. $2.99 billion disclosed. 79.7% verification rate. Three unicorns. HealthTech leads by deal count; FinTech/Insurance leads by dollars. Early-stage pipeline is strong (59% of deals). The question isn't whether Chicago can produce startups—it's whether they'll stay and scale here. This data says they're trying.",
    stats: [
      { label: 'Verified Deals', value: '64', trend: 'stable', trendValue: 'of 75 analyzed' },
      { label: 'Verification Rate', value: '79.7%', trend: 'up', trendValue: 'vs 49% initial' },
      { label: 'Removed', value: '11', trend: 'down', trendValue: 'Failed verification' },
    ],
    chartData: [
      { year: 'HealthTech', value: 18, label: '18 deals (28%)' },
      { year: 'FinTech', value: 11, label: '11 deals (17%)' },
      { year: 'Enterprise', value: 10, label: '10 deals (16%)' },
      { year: 'Deep Tech', value: 6, label: '6 deals (9%)' },
      { year: 'Other', value: 19, label: '19 deals (30%)' },
    ],
    chartLabel: 'Deal Count by Sector',
    startups: [],
    insights: "Diversified by deal count, concentrated by dollars. The HUB deal alone is 54% of funding.",
    futureTrend: "2026 prediction: Cross-sector fusion (Bio-Fin, Quantum-Finance) will define the next wave.",
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=2613&auto=format&fit=crop',
  },
];
